spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://db-postgresql-nyc1-04177-do-user-2364572-0.db.ondigitalocean.com:25060/table_fixer_dev
    username: doadmin
    password: yeylnisr3usov1iv
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2